---
language: java

dist: xenial

os: linux

jdk:
- openjdk8

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Verify
  - name: Build
    if: NOT commit_message =~ /chore\(release\)\:/ AND branch = main AND type = push AND fork = false
  - name: Release
    if: NOT commit_message =~ /chore\(release\)\:/ AND branch = main AND type = push AND fork = false
  - name: Deploy
    if: tag IS present
  
before_install:
  - sudo apt-get update
  - env | grep TRAVIS
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

jobs:
  include:
    - stage: Verify
      jdk: openjdk8
      install:
        - curl -s https://codecov.io/bash > $HOME/codecov-bash.sh && chmod +x $HOME/codecov-bash.sh
      script: 
        - mvn verify -fae -DskipITs $MVN_ARGS
      after_success:
        - build/publishCodeCoverage.sh

    - stage: Build
      jdk: openjdk8
      script: build/testScript.sh

    - stage: Release
      name: Release
      install:
        - sudo apt-get update
        - sudo apt-get install python
        - nvm install 12
        - npm install -g npm@6.x
        - pip install --user bump2version
        - npm install @semantic-release/changelog
        - npm install @semantic-release/exec
        - npm install @semantic-release/git
        - npm install @semantic-release/github
      script:
        - npx semantic-release
      before_deploy: build/prepareJavadoc.sh
      deploy:
        provider: pages
        on:
          branch: main
        skip_cleanup: true
        token: $GH_TOKEN
        local_dir: javadocs

    - stage: Deploy
      jdk: openjdk8
      script:
        - mvn deploy $MVN_ARGS -DskipITs -P central
