---
language: java

dist: xenial

os: linux

jdk:
- openjdk8
branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Build & Test
  - name: Release & Deployment
    if: branch = main AND type = push AND fork = false

before_install:
  - sudo apt-get update
  - env | grep TRAVIS
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

jobs:
  include:
    - stage: Build & Test
      install:
        - curl -s https://codecov.io/bash > $HOME/codecov-bash.sh && chmod +x $HOME/codecov-bash.sh
      script: mvn verify -fae -DskipITs $MVN_ARGS
      after_success:
        - build/publishCodeCoverage.sh

    - stage: Release & Deployment
      name: Release & Deployment
      jdk: openjdk8
      install:
        - sudo apt-get update
        - sudo apt-get install python
        - nvm install 12
        - npm install -g npm@6.x
        - pip install --user bump2version
        - npm install @semantic-release/changelog
        - npm install @semantic-release/exec
        - npm install @semantic-release/git
        - npm install @semantic-release/github
      script:
        - mvn clean package -DskipITs
        - npx semantic-release
        - mvn deploy $MVN_ARGS -DskipITs -P central
      deploy:
        provider: pages
        on:
          branch: main
        skip_cleanup: true
        token: $GH_TOKEN
        local_dir: target/site/apidocs